-- Book 1: Constructive Propositional Logic - Chapter Imports

import Content.B01_ConstructivePropositionalLogic.chapters.CS6501_2026_01_20

-- Propositions as Types (shallow embedding of constructive propositional logic)
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C00_introduction
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C01_conjunction
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C02_disjunction
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C03_falsity_negation
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C04_implication
import Content.B01_ConstructivePropositionalLogic.chapters.propAsTypes.C05_embedding_summary
