[book]
title = "Reasoning and Computation"
authors = ["Kevin Sullivan"]
language = "en"
multilingual = false
description = "Discrete Mathematics and Theory I in Lean 4"
src = "src"

[build]
build-dir = "book"

[output.html]
additional-js = [
    "assets/lean.min.js",
    "assets/mermaid.min.js",
    "assets/mermaid-init.js",
]

additional-css = ["css/custom.css"]

mathjax-support = true

git-repository-url = "https://github.com/kevinsullivan/dmtl4"

[output.html.playground.boring-prefixes]
lean = "# "

[preprocessor.toc]
command = "mdbook-toc"
depth = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.image-size]
command = "mdbook-image-size"
