[book]
title = "Reasoning and Computation"
authors = ["Kevin Sullivan"]
language = "en"
multilingual = false
description = "Reasoning and Computation: Discrete Mathematics and Theory I in Lean 4"
src = "src"

[build]
build-dir = "book"

[output.html]
additional-js = [
    "assets/lean.min.js",
    "assets/mermaid.min.js",
    "assets/mermaid-init.js",
]
mathjax-support = true
git-repository-url = "https://github.com/kevinsullivan/dmtl4"

[output.html.playground]
boring-prefixes = ["# "]

[preprocessor.toc]
command = "mdbook-toc"
depth = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.image-size]
command = "mdbook-image-size"

[output.pandoc.profile.pdf]
to = "latex"
output-file = "ReasoningAndComputation.pdf"
pdf-engine = "xelatex"
template = "/home/dev/.pandoc/templates/stix-math.latex"

[output.pandoc.profile.debug]
to = "latex"
output-file = "debug.tex"
template = "/home/dev/.pandoc/templates/stix-math.latex"
