/- @@@
# Equality in Lean

<!-- toc -->

Equality is one of the most basic concepts in mathematics, but
in a type theory like Lean's it has surprising depth. There are
three distinct notions of equality, each serving a different
purpose:

- **Definitional equality** (also called *judgmental equality*
  or *convertibility*): a kernel-level notion, not a type. Two
  expressions are definitionally equal when Lean's kernel can
  confirm they are interconvertible by computation and unfolding.
  No proof term is needed — the type checker verifies this
  automatically. Definitional equality is the strongest and most
  convenient notion, because Lean uses it silently in type
  checking, elaboration, and unification.
- **Propositional equality** (`Eq`): the inductive type `a = b`,
  which must be proved explicitly. When two terms are not
  definitionally equal but are still equal, you construct a
  proof term of this type.
- **Heterogeneous equality** (`HEq`): equality between terms
  whose types may differ. This arises mainly in dependent-type
  situations where ordinary `Eq` is too restrictive. When the
  two terms do have the same type, `HEq` and `Eq` are closely
  connected and can often be converted back and forth, but `Eq`
  should remain the default; treat `HEq` as a specialized tool
  for dependent situations.

Note that only `Eq` and `HEq` are equality *types*. Definitional
equality is a judgment of the kernel, not something you state or
prove inside the logic.

We will explore all three from the ground up, along with the key
proof techniques: reflexivity, symmetry, transitivity, substitution,
congruence, rewriting, and calculational chains. We finish with
type casts, decidable equality, and exercises.
@@@ -/

namespace Content.B07_Equality.chapters.CS6501_Equality

/- @@@
## Definitional Equality

Two expressions are *definitionally equal* (also called *judgmentally
equal* or *convertible*) when Lean's kernel can confirm they are
interconvertible by computation and unfolding. No proof is needed —
the type checker verifies this automatically. When two expressions
are definitionally equal, the `rfl` proof term can construct a
proof of their propositional equality (`Eq`) — but `rfl` itself
is a term of type `Eq`, not a certificate of the kernel judgment.
@@@ -/

-- 2 + 3 and 5 reduce to the same value
example : 2 + 3 = 5 := rfl

-- Function application: (fun x => x + 1) 4 reduces to 5
example : (fun x => x + 1) 4 = 5 := rfl

-- List.length [1, 2, 3] reduces to 3
example : List.length [1, 2, 3] = 3 := rfl

/- @@@
Use `#reduce` to see what Lean's kernel reduces a term to.
If two terms `#reduce` to the same thing, they are definitionally
equal and `rfl` will close the goal.
@@@ -/

#reduce 2 + 3           -- 5
#reduce (fun x => x + 1) 4   -- 5

/- @@@
Definitional equality is *silent* — the kernel handles it without
you writing anything. But not all true equalities are definitional.
For example, `0 + n = n` is true for every natural number, but it
is *not* definitional because `+` is defined by recursion on its
*second* argument. Lean cannot reduce `0 + n` without knowing what
`n` is. Proving such equalities requires the machinery of
propositional equality.
@@@ -/

/- @@@
This works because the definition of `Nat.add` (which implements
`+`) pattern-matches on its second argument. One of its defining
equations is `n + 0 = n`, so the kernel can reduce `n + 0` to `n`
directly — this is a computation rule generated by the definition,
not an extra axiom. No such defining equation reduces `0 + n`,
so that equality must be proved by induction.
@@@ -/

-- This works: Nat.add provides n + 0 = n by definition
example (n : Nat) : n + 0 = n := rfl

-- This does NOT work with rfl: no definitional rule for 0 + n
-- example (n : Nat) : 0 + n = n := rfl   -- ERROR

/- @@@
## Propositional Equality: The `Eq` Type

Lean's equality type is an inductive family with one constructor:

```
inductive Eq : α → α → Prop where
  | refl (a : α) : Eq a a
```

The notation `a = b` is sugar for `@Eq α a b`. The only way to
*construct* a proof of `a = b` is `Eq.refl a`, which requires
`a` and `b` to be definitionally equal. The tactic `rfl` applies
`Eq.refl` automatically.

The key insight: `Eq` has only one constructor, so any proof of
`a = b` must ultimately be built from `refl`. This means `a` and
`b` must be "the same" in a deep sense — possibly after reduction
and rewriting.
@@@ -/

#check @Eq              -- Eq : α → α → Prop
#check @Eq.refl         -- Eq.refl : (a : α) → a = a
#print Eq               -- inductive Eq : α → α → Prop

-- Explicit proof term vs rfl sugar
example : 42 = 42 := Eq.refl 42
example : 42 = 42 := rfl

-- Equality is a proposition — a type in Prop
#check (rfl : 1 + 1 = 2)       -- 1 + 1 = 2

/- @@@
### Equality is an Equivalence Relation

A binary relation `R` on a type `α` is an **equivalence relation**
if it satisfies three properties:

- **Reflexive**: `R a a` for all `a` — everything is related to itself.
- **Symmetric**: `R a b → R b a` — the relation works in both directions.
- **Transitive**: `R a b → R b c → R a c` — the relation chains.

Equality is the prototypical equivalence relation. The `Eq` type
gives us reflexivity directly (`Eq.refl`), and from the single
constructor `refl` we can derive symmetry and transitivity. Our
goal for the next few sections is to build up these three
properties, along with the key proof tool — **substitution** — that
makes symmetry and transitivity provable.
@@@ -/

/- @@@
## Elimination: `Eq.subst` and `▸`

The `Eq` type has one constructor (`refl`) — that's the
*introduction* rule. Now we need the *elimination* rule:
what can we do with a proof of `a = b`?

The answer is **substitution**. If `a = b` and you have a proof
of some property `P a`, then you can obtain a proof of `P b`.
The function `P` is called the *motive*.

```
Eq.subst : {a b : α} → a = b → P a → P b
```

In other words: equals can be substituted for equals in any context.
@@@ -/

#check @Eq.subst
  -- @Eq.subst : {α : Sort u} → {motive : α → Prop} →
  --             {a b : α} → a = b → motive a → motive b

/- @@@
Lean provides a convenient notation for substitution: `▸`
(typed as `\t` or `\blacktriangleleft`). Writing `h ▸ e` where
`h : a = b` rewrites occurrences of `b` with `a` in the expected
type, then checks that `e` has the rewritten type. It is the
term-mode analogue of the `rw` tactic.
@@@ -/

-- If n = m and n is even, then m is even (explicit Eq.subst with motive)
example (n m : Nat) (h_eq : n = m) (h_ev : n % 2 = 0) : m % 2 = 0 :=
  Eq.subst (motive := fun x => x % 2 = 0) h_eq h_ev

-- Same example using ▸ notation (Lean infers the motive)
example (n m : Nat) (h_eq : n = m) (h_ev : n % 2 = 0) : m % 2 = 0 :=
  h_eq ▸ h_ev

-- Substitution to prove n + 1 = m + 1 from n = m (explicit Eq.subst)
example (n m : Nat) (h : n = m) : n + 1 = m + 1 :=
  Eq.subst (motive := fun x => n + 1 = x + 1) h rfl

-- Same example using ▸ notation
example (n m : Nat) (h : n = m) : n + 1 = m + 1 :=
  h ▸ rfl

/- @@@
## Deriving Symmetry and Transitivity

With just `refl` (introduction) and `subst`/`▸` (elimination),
we can derive that equality is symmetric and transitive. These
are not additional axioms — they follow from the two we already
have.

### Symmetry

Given `h : a = b`, we want to prove `b = a`.
- The goal is `b = a`.
- We use `h ▸ rfl`: substitution rewrites the `b` in the goal
  to `a` (using `h : a = b`), giving the new goal `a = a`.
- `rfl` closes `a = a`.
@@@ -/

-- Symmetry derived from refl + subst
theorem eq_symm {a b : α} (h : a = b) : b = a :=
  h ▸ rfl

/- @@@
### Transitivity

Given `h1 : a = b` and `h2 : b = c`, we want to prove `a = c`.
- The goal is `a = c`.
- We use `h2 ▸ h1`: substitution rewrites the `c` in the goal
  to `b` (using `h2 : b = c`), giving the new goal `a = b`.
- `h1` is exactly a proof of `a = b`.
@@@ -/

-- Transitivity derived from subst
theorem eq_trans {a b c : α} (h1 : a = b) (h2 : b = c) : a = c :=
  h2 ▸ h1

/- @@@
### Proving Equality is an Equivalence Relation

We have now derived all three equivalence relation properties
from just the introduction rule (`refl`) and the elimination
rule (`subst`/`▸`):
@@@ -/

-- Reflexivity: directly from the constructor
theorem eq_refl (a : α) : a = a := rfl

-- Symmetry and transitivity: derived above
#check @eq_symm          -- a = b → b = a
#check @eq_trans         -- a = b → b = c → a = c

/- @@@
Lean's standard library provides these as `Eq.symm` and
`Eq.trans`. Now that we know where they come from, we can
use them freely.
@@@ -/

#check @Eq.symm         -- {a b : α} → a = b → b = a
#check @Eq.trans        -- {a b c : α} → a = b → b = c → a = c

-- Using Eq.symm: flip an equation (explicit)
example (h : 3 = 4) : 4 = 3 := Eq.symm h

-- Same example using dot notation
example (h : 3 = 4) : 4 = 3 := h.symm

-- Using Eq.trans: chain two equalities (explicit)
example (a b c : Nat) (h1 : a = b) (h2 : b = c) : a = c :=
  Eq.trans h1 h2

-- Same example using dot notation
example (a b c : Nat) (h1 : a = b) (h2 : b = c) : a = c :=
  h1.trans h2

/- @@@
### Tactic Proofs

The same facts are often easier to prove with tactics. The
`rw` tactic is the tactic-mode version of `▸` — it rewrites
the goal using an equality hypothesis.
@@@ -/

theorem eq_symm' {a b : α} (h : a = b) : b = a := by
  rw [h]

theorem eq_trans' {a b c : α} (h1 : a = b) (h2 : b = c) : a = c := by
  rw [h1, h2]

/- @@@
## Congruence: `congrArg` and `congr`

If `a = b`, then `f a = f b` for any function `f`. This is
*congruence* — functions respect equality.
@@@ -/

#check @congrArg   -- (f : α → β) → a = b → f a = f b
#check @congr      -- f = g → a = b → f a = g b
#check @congrFun   -- f = g → (a : α) → f a = g a

-- Applying a function to both sides of an equation
example (n m : Nat) (h : n = m) : n + 1 = m + 1 :=
  congrArg (· + 1) h

-- If two functions are equal and their arguments are equal,
-- then their results are equal
example (f g : Nat → Nat) (n m : Nat)
    (hfg : f = g) (hnm : n = m) : f n = g m :=
  congr hfg hnm

/- @@@
Congruence is how equalities propagate through expressions.
If you know `x = y`, you can conclude `f x = f y`, then
`g (f x) = g (f y)`, and so on — mechanically, one function
application at a time.

## The `rewrite` Tactic

The `rw` (rewrite) tactic is the workhorse for equational
reasoning in tactic mode. Given a proof `h : a = b`, the
tactic `rw [h]` replaces all occurrences of `a` with `b`
in the goal.
@@@ -/

-- Rewriting left to right
example (x y : Nat) (h : x = y) : x + x = y + y := by
  rw [h]

-- Rewriting right to left with ←
example (x y : Nat) (h : x = y) : y + y = x + x := by
  rw [← h]

-- Chaining multiple rewrites
example (a b c : Nat) (h1 : a = b) (h2 : b = c) : a + a = c + c := by
  rw [h1, h2]

/- @@@
### Rewriting in Hypotheses

Use `rw [h] at h'` to rewrite in a hypothesis rather than the goal.
@@@ -/

example (x y : Nat) (h : x = y) (h2 : x + 1 = 10) : y + 1 = 10 := by
  rw [h] at h2
  exact h2

/- @@@
### Directed Rewriting

Sometimes you need to control the direction. By default `rw [h]`
rewrites left-to-right (replacing `a` with `b` when `h : a = b`).
Use `rw [← h]` to go right-to-left (replacing `b` with `a`).
@@@ -/

example (x y z : Nat) (h1 : x = y) (h2 : z = y) : x = z := by
  rw [h1, ← h2]

/- @@@
## Calculational Proofs with `calc`

For longer chains of equational reasoning, Lean provides `calc`
blocks. Each step states an equality and justifies it.
@@@ -/

example (a b c d : Nat) (h1 : a = b) (h2 : b = c) (h3 : c = d) : a = d :=
  calc a = b := h1
    _ = c := h2
    _ = d := h3

-- A more interesting example with arithmetic
example (x y : Nat) (h : x = y) : (x + 1) * 2 = (y + 1) * 2 :=
  calc (x + 1) * 2 = (y + 1) * 2 := by rw [h]

-- calc works with other relations too (≤, <, etc.)
-- but here we focus on equality

/- @@@
### A Longer Calculational Proof

Let's prove that if `a = b` and `c = d`, then `a + c = b + d`.
@@@ -/

theorem add_eq_of_eq (a b c d : Nat)
    (hab : a = b) (hcd : c = d) : a + c = b + d :=
  calc a + c
    _ = b + c := by rw [hab]
    _ = b + d := by rw [hcd]

/- @@@
## Heterogeneous Equality: `HEq`

Lean's `Eq` requires both sides to have the *same* type:
`@Eq α a b` means `a : α` and `b : α`. But sometimes we need
to state that two values of *different* types are "equal" — this
arises with indexed families and dependent types.

Consider vectors (length-indexed lists). If `v : Vect α n` and
`w : Vect α m`, the statement `v = w` is not even well-typed when
`n ≠ m`, because `Vect α n` and `Vect α m` are different types.
Heterogeneous equality, `HEq`, solves this:

```
inductive HEq : {α : Sort u} → α → {β : Sort u} → β → Prop where
  | refl (a : α) : HEq a a
```

`HEq a b` (notation `a ≅ b`) says: `a` and `b` are equal, even
though they might have different types. But the only constructor
is `refl`, so `HEq a b` can only be proved when the types are
actually the same and `a` is definitionally equal to `b`.
@@@ -/

#check @HEq             -- HEq : α → β → Prop
#check @HEq.refl        -- HEq.refl : (a : α) → HEq a a
#print HEq

-- Converting between Eq and HEq
#check @heq_of_eq       -- a = b → HEq a b
#check @eq_of_heq       -- HEq a b → a = b  (when types match)

example (h : 3 = 3) : HEq 3 3 := heq_of_eq h
example (h : HEq (2 : Nat) 2) : (2 : Nat) = 2 := eq_of_heq h

/- @@@
### When Does `HEq` Arise?

Heterogeneous equality appears naturally when you work with
dependent types — particularly indexed inductive families.
Consider length-indexed vectors:
@@@ -/

-- Length-indexed vectors
inductive Vect (α : Type) : Nat → Type where
  | nil  : Vect α 0
  | cons : α → Vect α n → Vect α (n + 1)

/- @@@
Suppose we have a `Vect Nat (0 + n)` and a `Vect Nat n`. These
two vectors may hold the same data, but their types differ:
`Vect Nat (0 + n)` is not the same type as `Vect Nat n` because
`0 + n` is not definitionally equal to `n`. We cannot even
*state* `v1 = v2` with `Eq`, because `Eq` requires both sides
to have the same type. This is exactly where `HEq` is needed:
@@@ -/

-- Ordinary Eq cannot even state this — the types differ:
-- example (v : Vect Nat (0 + 3)) (w : Vect Nat 3) : v = w := ...  -- TYPE ERROR

-- HEq lets us at least state the question
example (v : Vect Nat (0 + 3)) (w : Vect Nat 3) : Prop := HEq v w

/- @@@
In practice, `HEq` goals often appear when Lean cannot unify
index expressions during dependent pattern matching. The usual
strategy is to rewrite the indices until the types match, then
convert to `Eq`.

---

**What follows is advanced material.** The sections above —
definitional equality, `Eq`, `rfl`, substitution, symmetry,
transitivity, congruence, `rw`, and `calc` — form the core
toolkit for equational reasoning in Lean. The remaining
sections cover machinery for *dependent* equality: casts,
transport, `Eq.rec`, and decidable equality. You will need
these when working with indexed families, but they build on
the core rather than replacing it.

---

## Type Casts and Transport

In the non-dependent goals we have seen so far, `rw` and `▸`
rewrite terms but leave their types alone. In dependent goals,
rewriting may change the *type family* itself — a `Vect α n`
must become a `Vect α m` when an index changes. This is why
casts and transport appear: they are the tools for crossing the
gap between propositionally equal but not definitionally equal
types.

When two types are provably equal, we can *cast* a value from
one type to the other. The function `cast` does this:

```
cast : {α β : Sort u} → α = β → α → β
```

Given a proof that `α = β` (an equality of types), `cast`
converts a value of type `α` into a value of type `β`.
@@@ -/

#check @cast           -- cast : α = β → α → β

-- If we know Nat = Nat (trivially), we can cast
example : cast rfl 42 = 42 := rfl

/- @@@
### `Eq.mpr` and `Eq.mp`

Closely related to `cast` are `Eq.mp` and `Eq.mpr`:

- `Eq.mp  : α = β → α → β`  (forward: same as `cast`)
- `Eq.mpr : α = β → β → α`  (backward: cast in reverse)

These arise frequently in tactic proofs when the goal type
needs to be transformed by a type equality.
@@@ -/

#check @Eq.mp          -- α = β → α → β
#check @Eq.mpr         -- α = β → β → α

/- @@@
### Cast and HEq

There is a fundamental connection: `cast h a` is heterogeneously
equal to `a`. Casting does not change the "value" — it only changes
the type annotation. This is captured by:
@@@ -/

#check @cast_heq       -- (h : α = β) → (a : α) → HEq (cast h a) a

/- @@@
This says: after casting, the result is `HEq`-equal to the original.
The value did not change; only the type wrapper did.

## Dependent Casts: `Eq.rec` and Transport

The `cast` function handles a simple case: converting a value of
type `α` to type `β` when `α = β`. But in dependently typed
programming, we often face a harder problem: we have a value in
a *family* of types indexed by some value, and we need to move
it to a different index.

For example, suppose we have a `Vect α n` and a proof that
`n = m`. We need a `Vect α m`. The plain `cast` can do this
if we build the right type equality, but the fundamental tool
underlying all of this is **`Eq.rec`** — the *recursor*
(eliminator) for the equality type.

### `Eq.rec`: The Eliminator for Equality

Every inductive type in Lean comes with a recursor. For `Eq`,
the recursor says: if you can produce something when the two
sides are the same (the `refl` case), then you can produce it
whenever the two sides are provably equal.
@@@ -/

#check @Eq.rec
-- @Eq.rec : {α : Sort u} →
--   {a : α} →
--   {motive : (b : α) → a = b → Sort v} →
--   motive a rfl →
--   {b : α} →
--   (h : a = b) →
--   motive b h

/- @@@
Read the type carefully:
- `a : α` is a fixed value.
- `motive` is a dependent function: given any `b` and a proof
  that `a = b`, it returns a *type*.
- You supply a value of `motive a rfl` — the case where `b` is
  just `a` and the proof is `rfl`.
- Given any `b` and proof `h : a = b`, you get back `motive b h`.

This is the most general form. The equality proof `h` "transports"
your value from the `a` fiber to the `b` fiber of the motive.

Here are two examples with all arguments written explicitly:
@@@ -/

-- Symmetry via Eq.rec
-- motive: fun (x : Nat) (_ : a = x) => x = a
-- base case (x = a, proof = rfl): need a = a, which is rfl
-- result: given h : a = b, get b = a
example (a b : Nat) (h : a = b) : b = a :=
  @Eq.rec Nat a (fun x _ => x = a) rfl b h

-- Transporting a predicate via Eq.rec
-- motive: fun (x : Nat) (_ : a = x) => x % 2 = 1
-- base case: a % 2 = 1, which is hodd
-- result: given h : a = b, get b % 2 = 1
example (a b : Nat) (h : a = b) (hodd : a % 2 = 1) : b % 2 = 1 :=
  @Eq.rec Nat a (fun x _ => x % 2 = 1) hodd b h

/- @@@
### `Eq.ndrec`: The Non-Dependent Version

In practice, the motive often does not depend on the proof `h`
itself — only on `b`. Lean provides `Eq.ndrec` (non-dependent
rec) for this simpler case:
@@@ -/

#check @Eq.ndrec
-- @Eq.ndrec : {α : Sort u} →
--   {a : α} →
--   {motive : α → Sort v} →
--   motive a →
--   {b : α} →
--   a = b →
--   motive b

/- @@@
This says: given a type family `motive : α → Sort v`, a value
in `motive a`, and a proof `a = b`, produce a value in `motive b`.
This is exactly *transport* — carrying data along an equality proof.

The same two examples, now with `Eq.ndrec` — note the motive
takes only `x`, not `x` and a proof:
@@@ -/

-- Symmetry via Eq.ndrec
-- motive: fun (x : Nat) => x = a  (no proof argument)
example (a b : Nat) (h : a = b) : b = a :=
  @Eq.ndrec Nat a (fun x => x = a) rfl b h

-- Congruence via Eq.ndrec
-- motive: fun (x : Nat) => a + 1 = x + 1
-- base case: a + 1 = a + 1, which is rfl
example (a b : Nat) (h : a = b) : a + 1 = b + 1 :=
  @Eq.ndrec Nat a (fun x => a + 1 = x + 1) rfl b h

/- @@@
### Transport in Action

Let's define a transport function and use it with our `Vect` type.
@@@ -/

-- Transport: move a value along an equality of indices
def transport {α : Sort u} {a b : α}
    (motive : α → Sort v) (h : a = b) (x : motive a) : motive b :=
  h ▸ x

-- Transport a vector from length n to length m
def Vect.cast {α : Type} {n m : Nat}
    (h : n = m) (v : Vect α n) : Vect α m :=
  transport (Vect α) h v

-- Example: transport across a trivial equality
example : Vect.cast rfl (Vect.cons 1 (Vect.cons 2 Vect.nil))
    = Vect.cons 1 (Vect.cons 2 Vect.nil) := by rfl

/- @@@
### The Dependent Cast Problem

Here is the motivating problem. We know that `0 + n = n` (we
prove it below as `zero_add`). So a `Vect α (0 + n)` should
be usable as a `Vect α n`. But Lean's type checker does not
see `0 + n` and `n` as definitionally equal — it needs a proof.
(In contrast, `n + 0` *does* reduce to `n` by definition, because
`+` recurses on its second argument.)

This is where dependent casts are essential: they let us cross
the gap between propositionally equal but not definitionally
equal indices.
@@@ -/

-- This does NOT type-check without a cast:
-- example (v : Vect Nat (0 + n)) : Vect Nat n := v   -- ERROR

-- We need transport with Nat.zero_add
def Vect.zeroAddCast {α : Type} {n : Nat}
    (v : Vect α (0 + n)) : Vect α n :=
  transport (Vect α) (Nat.zero_add n) v

-- We can also go the other direction
def Vect.zeroAddCast' {α : Type} {n : Nat}
    (v : Vect α n) : Vect α (0 + n) :=
  transport (Vect α) (Nat.zero_add n).symm v

/- @@@
### Transport Preserves Identity (up to HEq)

A key property: transporting by `rfl` does nothing. And more
generally, the transported value is heterogeneously equal to the
original — the "content" is the same, only the type index changed.
@@@ -/

-- Transport by rfl is the identity
theorem transport_rfl {α : Sort u} {a : α}
    (motive : α → Sort v) (x : motive a) :
    transport motive rfl x = x := rfl

-- Transport preserves value up to HEq
theorem transport_heq {α : Sort u} {a b : α}
    (motive : α → Sort v) (h : a = b) (x : motive a) :
    HEq (transport motive h x) x := by
  subst h
  exact HEq.refl x

/- @@@
### `Eq.rec` vs `cast` vs `▸`

These are all the same mechanism at different levels of
abstraction:

| Tool | What it does |
|---|---|
| `Eq.rec` | The primitive eliminator — fully dependent motive |
| `Eq.ndrec` | Non-dependent version — motive ignores the proof |
| `cast` | Special case: motive is `id`, transporting between equal types |
| `▸` / `subst` | Tactic/term notation — Lean infers the motive |
| `transport` (ours) | A named wrapper around `▸` for indexed families |

In practice, you'll most often use `▸` or `subst` in term mode,
and `rw`/`simp` in tactic mode. Reaching for `Eq.rec` directly
is rare but sometimes necessary when Lean cannot infer the motive.
@@@ -/

-- All of these are the same:
example (n : Nat) (h : 0 + n = n) (v : Vect Nat (0 + n)) : Vect Nat n :=
  cast (congrArg (Vect Nat) h) v

example (n : Nat) (h : 0 + n = n) (v : Vect Nat (0 + n)) : Vect Nat n :=
  h ▸ v

example (n : Nat) (h : 0 + n = n) (v : Vect Nat (0 + n)) : Vect Nat n :=
  transport (Vect Nat) h v

/- @@@
## Decidable Equality

So far, equality has been a *proposition* — something we prove in
`Prop`. But sometimes we need to *compute* whether two values are
equal at runtime, inside programs. This is **decidable equality**.

A type has decidable equality when there is an algorithm that,
given any two values, returns either a proof that they are equal
or a proof that they are not. In Lean, this is the `DecidableEq`
typeclass:

```
class DecidableEq (α : Sort u) where
  decEq : (a b : α) → Decidable (a = b)
```

The `Decidable` type is either `isTrue h` (carrying a proof of
the proposition) or `isFalse h` (carrying a proof of its negation).
@@@ -/

#check @DecidableEq     -- (α : Sort u) → Sort (max 1 u)
#check @Decidable       -- Prop → Type

-- Nat has decidable equality
#check (inferInstance : DecidableEq Nat)

-- We can compute equality at runtime
#eval decide (3 = 3)       -- true
#eval decide (3 = 4)       -- false
#eval decide ("hello" = "hello")   -- true

/- @@@
### `BEq` vs `Eq`

Lean has two distinct equality interfaces:

- **`Eq`** (`=`): propositional equality in `Prop`. Proof-relevant.
  Used in theorems and specifications.
- **`BEq`** (`==`): boolean equality returning `Bool`. Used in
  programs and `#eval`.

They are connected, but the connection requires a *lawful* `BEq`
instance — one that agrees with propositional equality. For
Lean's built-in types (Nat, String, etc.) this holds: `(a == b)
= true ↔ a = b`. For custom types, the `BEq` instance must be
implemented correctly for this equivalence to hold.
@@@ -/

-- BEq returns a Bool
#eval (3 : Nat) == 3         -- true
#eval (3 : Nat) == 4         -- false

-- Eq returns a Prop
#check (3 : Nat) = 3         -- Prop

-- The decide tactic bridges the gap:
-- it turns a Decidable proposition into a proof
example : (3 : Nat) = 3 := by decide
example : (3 : Nat) ≠ 4 := by decide

/- @@@
### Using `decide` in Proofs

The `decide` tactic works for any `Decidable` proposition. It
runs the decision procedure and, if the result is `isTrue h`,
extracts the proof `h`. This is powerful for concrete computations.
@@@ -/

example : 10 * 10 = 100 := by decide
example : "abc".length = 3 := by decide
example : ¬ (7 = 8) := by decide

/- @@@
For symbolic (variable-containing) goals, `decide` cannot help —
you need `rfl`, `rw`, or induction.

## A Proof by Induction: `0 + n = n`

We observed earlier that `0 + n = n` is not definitional. Let's
prove it by induction on `n`. This uses everything we've learned:
`rfl` for the base case, `rw` for the inductive step.
@@@ -/

theorem zero_add (n : Nat) : 0 + n = n := by
  induction n with
  | zero => rfl
  | succ n' ih =>
    -- Goal: 0 + (n' + 1) = n' + 1
    -- ih : 0 + n' = n'
    -- Nat.add_succ rewrites 0 + (n' + 1) to (0 + n') + 1
    rw [Nat.add_succ, ih]

/- @@@
The base case is definitional: `0 + 0 = 0` reduces by definition.
The inductive step rewrites using the induction hypothesis. This is
the pattern for most arithmetic proofs about natural numbers.

### Another Example: Commutativity of Addition

We chain together two lemmas to prove `a + b = b + a`.
@@@ -/

-- We use Nat.add_comm from the standard library
#check @Nat.add_comm    -- ∀ (n m : Nat), n + m = m + n

example (a b : Nat) : a + b = b + a := Nat.add_comm a b

-- Let's also see it as a calc proof
example (a b : Nat) : a + b = b + a :=
  calc a + b = b + a := Nat.add_comm a b

/- @@@
## Summary

| Concept | Type/Tactic | Purpose |
|---|---|---|
| Definitional equality | (kernel judgment) | Interconvertible by computation/unfolding |
| `Eq` / `rfl` | `a = b`, `Eq.refl` | Propositional equality |
| `Eq.symm` | `a = b → b = a` | Flip an equation |
| `Eq.trans` | `a = b → b = c → a = c` | Chain equations |
| `Eq.subst` / `▸` | `a = b → P a → P b` | Substitute equals for equals |
| `congrArg` | `a = b → f a = f b` | Functions respect equality |
| `rw` | tactic | Rewrite in goal or hypothesis |
| `calc` | proof block | Chain of equational steps |
| `HEq` | `HEq a b` | Equality across types |
| `cast` | `α = β → α → β` | Convert between equal types |
| `Eq.rec` | eliminator | Dependent elimination on equality proofs |
| `Eq.ndrec` | eliminator | Non-dependent transport along equality |
| `transport` | `motive a → motive b` | Move data between indexed types |
| `DecidableEq` | typeclass | Runtime equality checking |
| `BEq` / `==` | typeclass | Boolean equality for programs |
| `decide` | tactic | Prove decidable propositions |

## Additional Resources

- [CS1: Programming, Certified](https://kevinsullivan.github.io/Lean4CS1/) —
  An introductory programming course in Lean 4 that integrates
  formal specification and automated proof verification from day
  one, teaching data types, functions, recursion, and the
  Curry-Howard correspondence.

@@@ -/

/- @@@
## Exercises

Try to replace each `sorry` with an actual proof. Use `rfl`, `rw`,
`Eq.symm`, `Eq.trans`, `congrArg`, `calc`, and induction as needed.
@@@ -/

-- Exercise 1: Simple reflexivity
theorem ex_refl : 7 = 7 := sorry

-- Exercise 2: Symmetry
theorem ex_symm (a b : Nat) (h : a = b) : b = a := sorry

-- Exercise 3: Transitivity
theorem ex_trans (a b c : Nat) (h1 : a = b) (h2 : b = c) : a = c := sorry

-- Exercise 4: Congruence
theorem ex_congr (n m : Nat) (h : n = m) : n * 2 = m * 2 := sorry

-- Exercise 5: Rewriting
theorem ex_rw (x y z : Nat) (h1 : x = y + 1) (h2 : y = z) : x = z + 1 := sorry

-- Exercise 6: Calc block
theorem ex_calc (a b c : Nat) (h1 : a = b + 1) (h2 : b = c + 1) : a = c + 2 := sorry

-- Exercise 7: Induction (harder)
theorem ex_zero_add (n : Nat) : 0 + n = n := sorry

-- Exercise 8: Using decide
theorem ex_decide : 15 % 5 = 0 := sorry

/- @@@
### Advanced Exercises

These exercises use dependent casts and transport from the
second half of the chapter.
@@@ -/

-- Exercise 9: Transport a vector
-- Given a Vect Nat (0 + n), produce a Vect Nat n
-- Hint: use transport with Nat.zero_add
def ex_transport (n : Nat) (v : Vect Nat (0 + n)) : Vect Nat n := sorry

-- Exercise 10: Transport preserves HEq
-- Show that transporting v gives something HEq to v
-- Hint: what happens when you subst the equality proof?
theorem ex_transport_heq (n m : Nat) (h : n = m) (v : Vect Nat n) :
    HEq (transport (Vect Nat) h v) v := sorry

-- Exercise 11: Round-trip cast
-- Transport forward then back yields the original value
-- Hint: what is transport ... rfl?
theorem ex_round_trip (n m : Nat) (h : n = m) (v : Vect Nat n) :
    transport (Vect Nat) h.symm (transport (Vect Nat) h v) = v := sorry

end Content.B07_Equality.chapters.CS6501_Equality
